# Generated by Django 4.0.10 on 2023-04-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_alter_mood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateField(auto_created=True, default='11', null=True),
        ),
    ]
