# Generated by Django 4.0.10 on 2023-04-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_alter_mood_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, null=True)),
                ('user', models.CharField(max_length=100)),
                ('mood', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
