# Generated by Django 4.0.10 on 2023-04-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0004_moodmodel_delete_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
