# Generated by Django 4.0.10 on 2023-04-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0005_alter_moodmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('input', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MoodModel',
        ),
    ]
