# Generated by Django 4.0.10 on 2023-05-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0006_mood_delete_moodmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('tweet', models.CharField(max_length=100)),
                ('toxic', models.CharField(max_length=6)),
                ('severe_toxic', models.CharField(max_length=6)),
                ('obscene', models.CharField(max_length=6)),
                ('threat', models.CharField(max_length=6)),
                ('insult', models.CharField(max_length=6)),
                ('identity_hate', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('tweeter_username', models.CharField(blank=True, max_length=200, null=True)),
                ('registered', models.CharField(blank=True, default='OFF', max_length=200, null=True)),
            ],
        ),
    ]
