# Generated by Django 4.0.10 on 2023-04-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_dob', models.DateField(auto_now_add=True, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_diagnoses', models.TextField(blank=True, max_length=1500, null=True)),
                ('patient_drugs', models.TextField(blank=True, max_length=1500, null=True)),
                ('is_suicidal', models.BooleanField(default=False)),
                ('has_been_sectioned', models.BooleanField(default=False)),
                ('is_sectioned', models.BooleanField(default=False)),
                ('is_violent', models.BooleanField(default=False)),
                ('children_count', models.IntegerField(blank=True, default=0, null=True)),
                ('patient_history', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
