# Generated by Django 4.0.10 on 2023-04-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='record',
        ),
    ]
