# Generated by Django 4.0.10 on 2023-04-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0005_patient_appointment_alert_patient_has_been_sectioned_and_more'),
        ('doctor', '0044_appointment_message'),
        ('record_system', '0002_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnoses_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnoses', models.CharField(blank=True, max_length=64, null=True)),
                ('date_of_diagnosis', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='appointment_notes',
            fields=[
                ('appointment_notes_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('next_appointment', models.DateField(auto_now_add=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.appointment')),
                ('diagnoses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record_system.diagnoses_info')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('prescriptions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
    ]
