# Generated by Django 4.0.10 on 2023-04-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_system', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_notes',
            name='prescriptions',
        ),
        migrations.AlterField(
            model_name='appointment_notes',
            name='diagnoses',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='diagnoses_info',
        ),
    ]
