# Generated by Django 4.0.10 on 2023-04-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_user_login_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointment_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_been_sectioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_on_suicide_watch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_violent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescriptions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
